/*
** hunt.c for Raytracer2 in /gfx_raytracer2/src/shape
**
** Made by Antoine Baché
** Login   <bache_a@epitech.net>
**
** Started on  Sun May 15 03:24:57 2016 Antoine Baché
** Last update Sun May 22 20:11:43 2016 Arthur ARNAUD
*/

#include "solver.h"
#include "engine/intersect.h"
#include "engine/object.h"
#include "tools/memory.h"

static void	get_dist_hunt(t_obj *obj, t_ray *ray, t_intersect *inter,
			       t_vec3 tmp)
{
  double	s[7];

  s[0] = 12.0 * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y + 24.0 * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 12.0 * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 12.0 * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 12.0 * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 12.0 * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 12.0 * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 4.0 * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 4.0 * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 4.0 * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z;
  s[1] = 48.0 * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y + 48.0 * tmp.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 48.0 * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.y + 48.0 * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z * ray->dir.z + 48.0 * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z * ray->dir.z + 24.0 * tmp.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 24.0 * tmp.x * ray->dir.x * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 24.0 * tmp.y * ray->dir.y * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 24.0 * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 24.0 * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 24.0 * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 24.0 * tmp.y * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.y + 48.0 * tmp.z * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.z + 24.0 * tmp.z * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.z + 24.0 * tmp.z * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.z;
  s[2] = -150.0 * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y + 72.0 * tmp.x * tmp.x * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y + 72.0 * tmp.y * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y + 24.0 * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.y - 960.0 * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 72.0 * tmp.x * tmp.x * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 24.0 * tmp.y * tmp.y * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 72.0 * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z * ray->dir.z + 24.0 * tmp.x * tmp.x * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 72.0 * tmp.y * tmp.y * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 72.0 * tmp.z * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z - 528.0 * ray->dir.y * ray->dir.y * ray->dir.z * ray->dir.z + 96.0 * tmp.x * tmp.y * ray->dir.x * ray->dir.y * ray->dir.z * ray->dir.z + 96.0 * tmp.x * tmp.y * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.y + 96.0 * tmp.x * tmp.z * ray->dir.x * ray->dir.z * ray->dir.z * ray->dir.z + 96.0 * tmp.y * tmp.z * ray->dir.y * ray->dir.z * ray->dir.z * ray->dir.z + 60.0 * tmp.x * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 12.0 * tmp.y * tmp.y * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 12.0 * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 87.0 * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.x + 12.0 * tmp.x * tmp.x * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 60.0 * tmp.y * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 12.0 * tmp.z * tmp.z * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y - 129.0 * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.y + 12.0 * tmp.x * tmp.x * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 12.0 * tmp.y * tmp.y * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 60.0 * tmp.z * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 276.0 * ray->dir.z * ray->dir.z * ray->dir.z * ray->dir.z + 96.0 * tmp.x * tmp.y * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.y + 96.0 * tmp.x * tmp.z * ray->dir.x * ray->dir.y * ray->dir.y * ray->dir.z + 96.0 * tmp.x * tmp.z * ray->dir.x * ray->dir.x * ray->dir.x * ray->dir.z + 96.0 * tmp.y * tmp.z * ray->dir.y * ray->dir.y * ray->dir.y * ray->dir.z + 96.0 * tmp.y * tmp.z * ray->dir.x * ray->dir.x * ray->dir.y * ray->dir.z;
  s[3] = 144.0 * tmp.x * tmp.y * tmp.y * ray->dir.x * ray->dir.y * ray->dir.y + 48.0 * tmp.x * tmp.z * tmp.z * ray->dir.x * ray->dir.y * ray->dir.y + 48.0 * tmp.x * tmp.x * tmp.x * ray->dir.x * ray->dir.y * ray->dir.y - 300.0 * tmp.x * ray->dir.x * ray->dir.y * ray->dir.y + 48.0 * tmp.x * tmp.y * tmp.y * ray->dir.x * ray->dir.z * ray->dir.z + 144.0 * tmp.x * tmp.z * tmp.z * ray->dir.x * ray->dir.z * ray->dir.z + 48.0 * tmp.x * tmp.x * tmp.x * ray->dir.x * ray->dir.z * ray->dir.z - 1920.0 * tmp.x * ray->dir.x * ray->dir.z * ray->dir.z + 144.0 * tmp.y * tmp.z * tmp.z * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.y * tmp.y * tmp.y * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.x * tmp.x * tmp.y * ray->dir.y * ray->dir.z * ray->dir.z - 1056.0 * tmp.y * ray->dir.y * ray->dir.z * ray->dir.z + 48.0 * tmp.x * tmp.y * tmp.y * ray->dir.x * ray->dir.x * ray->dir.x + 48.0 * tmp.x * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.x + 80.0 * tmp.x * tmp.x * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x + 348.0 * tmp.x * ray->dir.x * ray->dir.x * ray->dir.x + 48.0 * tmp.y * tmp.z * tmp.z * ray->dir.y * ray->dir.y * ray->dir.y + 80.0 * tmp.y * tmp.y * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y + 48.0 * tmp.x * tmp.x * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y - 516.0 * tmp.y * ray->dir.y * ray->dir.y * ray->dir.y + 80.0 * tmp.z * tmp.z * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z + 48.0 * tmp.x * tmp.x * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z + 48.0 * tmp.y * tmp.y * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z + 1104.0 * tmp.z * ray->dir.z * ray->dir.z * ray->dir.z + 48.0 * tmp.y * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.y + 48.0 * tmp.y * tmp.y * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y - 300.0 * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y + 144.0 * tmp.x * tmp.x * tmp.y * ray->dir.x * ray->dir.x * ray->dir.y + 48.0 * tmp.z * tmp.z * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z - 1920.0 * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z + 144.0 * tmp.x * tmp.x * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z + 48.0 * tmp.y * tmp.y * tmp.z * ray->dir.x * ray->dir.x * ray->dir.z + 48.0 * tmp.z * tmp.z * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z + 48.0 * tmp.x * tmp.x * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z + 144.0 * tmp.y * tmp.y * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z - 1056.0 * tmp.z * ray->dir.y * ray->dir.y * ray->dir.z + 192.0 * tmp.x * tmp.y * tmp.z * ray->dir.x * ray->dir.y * ray->dir.z;
  s[4] = 522.0 * tmp.x * tmp.x * ray->dir.x * ray->dir.x - 150.0 * tmp.y * tmp.y * ray->dir.x * ray->dir.x + 72.0 * tmp.x * tmp.x * tmp.y * tmp.y * ray->dir.x * ray->dir.x - 960.0 * tmp.z * tmp.z * ray->dir.x * ray->dir.x + 72.0 * tmp.x * tmp.x * tmp.z * tmp.z * ray->dir.x * ray->dir.x + 24.0 * tmp.y * tmp.y * tmp.z * tmp.z * ray->dir.x * ray->dir.x + 84.0 * ray->dir.x * ray->dir.x + 60.0 * tmp.x * tmp.x * tmp.x * tmp.x * ray->dir.x * ray->dir.x + 12.0 * tmp.y * tmp.y * tmp.y * tmp.y * ray->dir.x * ray->dir.x + 12.0 * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.x * ray->dir.x + 1380.0 * ray->dir.y * ray->dir.y - 150.0 * tmp.x * tmp.x * ray->dir.y * ray->dir.y + 72.0 * tmp.x * tmp.x * tmp.y * tmp.y * ray->dir.y * ray->dir.y - 774.0 * tmp.y * tmp.y * ray->dir.y * ray->dir.y + 24.0 * tmp.x * tmp.x * tmp.z * tmp.z * ray->dir.y * ray->dir.y + 72.0 * tmp.y * tmp.y * tmp.z * tmp.z * ray->dir.y * ray->dir.y - 528.0 * tmp.z * tmp.z * ray->dir.y * ray->dir.y + 12.0 * tmp.x * tmp.x * tmp.x * tmp.x * ray->dir.y * ray->dir.y + 60.0 * tmp.y * tmp.y * tmp.y * tmp.y * ray->dir.y * ray->dir.y + 12.0 * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.y * ray->dir.y + 4620.0 * ray->dir.z * ray->dir.z - 960.0 * tmp.x * tmp.x * ray->dir.z * ray->dir.z + 24.0 * tmp.x * tmp.x * tmp.y * tmp.y * ray->dir.z * ray->dir.z - 528.0 * tmp.y * tmp.y * ray->dir.z * ray->dir.z + 72.0 * tmp.x * tmp.x * tmp.z * tmp.z * ray->dir.z * ray->dir.z + 72.0 * tmp.y * tmp.y * tmp.z * tmp.z * ray->dir.z * ray->dir.z + 1656.0 * tmp.z * tmp.z * ray->dir.z * ray->dir.z + 12.0 * tmp.x * tmp.x * tmp.x * tmp.x * ray->dir.z * ray->dir.z + 12.0 * tmp.y * tmp.y * tmp.y * tmp.y * ray->dir.z * ray->dir.z + 60.0 * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.z * ray->dir.z + 96.0 * tmp.x * tmp.y * tmp.z * tmp.z * ray->dir.x * ray->dir.y + 96.0 * tmp.x * tmp.y * tmp.y * tmp.y * ray->dir.x * ray->dir.y + 96.0 * tmp.x * tmp.x * tmp.x * tmp.y * ray->dir.x * ray->dir.y - 600.0 * tmp.x * tmp.y * ray->dir.x * ray->dir.y + 96.0 * tmp.x * tmp.z * tmp.z * tmp.z * ray->dir.x * ray->dir.z + 96.0 * tmp.x * tmp.y * tmp.y * tmp.z * ray->dir.x * ray->dir.z + 96.0 * tmp.x * tmp.x * tmp.x * tmp.z * ray->dir.x * ray->dir.z - 3840.0 * tmp.x * tmp.z * ray->dir.x * ray->dir.z + 96.0 * tmp.y * tmp.z * tmp.z * tmp.z * ray->dir.y * ray->dir.z + 96.0 * tmp.y * tmp.y * tmp.y * tmp.z * ray->dir.y * ray->dir.z - 2112.0 * tmp.y * tmp.z * ray->dir.y * ray->dir.z + 96.0 * tmp.x * tmp.x * tmp.y * tmp.z * ray->dir.y * ray->dir.z;
  s[5] = 48.0 * tmp.x * tmp.x * tmp.x * tmp.y * tmp.y * ray->dir.x - 300.0 * tmp.x * tmp.y * tmp.y * ray->dir.x + 48.0 * tmp.x * tmp.y * tmp.y * tmp.z * tmp.z * ray->dir.x + 48.0 * tmp.x * tmp.x * tmp.x * tmp.z * tmp.z * ray->dir.x - 1920.0 * tmp.x * tmp.z * tmp.z * ray->dir.x + 348.0 * tmp.x * tmp.x * tmp.x * ray->dir.x + 24.0 * tmp.x * tmp.y * tmp.y * tmp.y * tmp.y * ray->dir.x + 24.0 * tmp.x * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.x + 24.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.x * ray->dir.x + 168.0 * tmp.x * ray->dir.x + 48.0 * tmp.y * tmp.y * tmp.y * tmp.z * tmp.z * ray->dir.y + 48.0 * tmp.x * tmp.x * tmp.y * tmp.z * tmp.z * ray->dir.y - 1056.0 * tmp.y * tmp.z * tmp.z * ray->dir.y + 48.0 * tmp.x * tmp.x * tmp.y * tmp.y * tmp.y * ray->dir.y - 516.0 * tmp.y * tmp.y * tmp.y * ray->dir.y + 24.0 * tmp.y * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.y + 24.0 * tmp.y * tmp.y * tmp.y * tmp.y * tmp.y * ray->dir.y + 2760.0 * tmp.y * ray->dir.y - 300.0 * tmp.x * tmp.x * tmp.y * ray->dir.y + 24.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.y * ray->dir.y + 48.0 * tmp.x * tmp.x * tmp.z * tmp.z * tmp.z * ray->dir.z + 48.0 * tmp.y * tmp.y * tmp.z * tmp.z * tmp.z * ray->dir.z + 1104.0 * tmp.z * tmp.z * tmp.z * ray->dir.z + 24.0 * tmp.z * tmp.z * tmp.z * tmp.z * tmp.z * ray->dir.z + 9240.0 * tmp.z * ray->dir.z - 1920.0 * tmp.x * tmp.x * tmp.z * ray->dir.z + 48.0 * tmp.x * tmp.x * tmp.y * tmp.y * tmp.z * ray->dir.z - 1056.0 * tmp.y * tmp.y * tmp.z * ray->dir.z + 24.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.z * ray->dir.z + 24.0 * tmp.y * tmp.y * tmp.y * tmp.y * tmp.z * ray->dir.z;
  s[6] = -4900.0 + 84.0 * tmp.x * tmp.x + 1380.0 * tmp.y * tmp.y - 150.0 * tmp.x * tmp.x * tmp.y * tmp.y + 12.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.y * tmp.y + 4620.0 * tmp.z * tmp.z - 960.0 * tmp.x * tmp.x * tmp.z * tmp.z + 24.0 * tmp.x * tmp.x * tmp.y * tmp.y * tmp.z * tmp.z - 528.0 * tmp.y * tmp.y * tmp.z * tmp.z + 12.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.z * tmp.z + 12.0 * tmp.y * tmp.y * tmp.y * tmp.y * tmp.z * tmp.z + 87.0 * tmp.x * tmp.x * tmp.x * tmp.x + 12.0 * tmp.x * tmp.x * tmp.y * tmp.y * tmp.y * tmp.y - 129.0 * tmp.y * tmp.y * tmp.y * tmp.y + 12.0 * tmp.x * tmp.x * tmp.z * tmp.z * tmp.z * tmp.z + 12.0 * tmp.y * tmp.y * tmp.z * tmp.z * tmp.z * tmp.z + 276.0 * tmp.z * tmp.z * tmp.z * tmp.z + 4.0 * tmp.x * tmp.x * tmp.x * tmp.x * tmp.x * tmp.x + 4.0 * tmp.y * tmp.y * tmp.y * tmp.y * tmp.y * tmp.y + 4.0 * tmp.z * tmp.z * tmp.z * tmp.z * tmp.z * tmp.z;
  if ((inter->dist = solver_n_degree(s, 6)) == NOT_A_SOLUTION)
    inter->dist = -1.0;
}

t_intersect	get_intersect_hunt(t_obj *obj, t_ray *ray)
{
  t_intersect	inter;

  inter.dir = ray->dir;
  inter.mat = obj->mat;
  inter.dist = -1.0;
  get_dist_hunt(obj, ray, &inter, ray->pos);
  if (inter.dist <= 0.0)
    return (inter);
  inter.pos = add_vec3(mult_vec3(ray->dir, inter.dist), ray->pos);
  calc_normale_hunt(&inter);
  return (inter);
}
